apiVersion: v1
kind: Pod
metadata:
  name: nginx-env-pod
spec:
  containers:
  - name: nginx-container
    image: nginx
    env:
    - name: MY_VARIABLE
      value: "Hello, Kubernetes!"
    ports:
    - containerPort: 80
