apiVersion: v1
kind: Pod
metadata:
  name: nginx-pv-pod
spec:
  containers:
  - name: nginx-container
    image: nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: html-volume
    ports:
    - containerPort: 80
  volumes:
  - name: html-volume
    persistentVolumeClaim:
      claimName: nginx-pvc
